[project]
name = "mtrick"
version = "0.6.2"
description = "A local, zero-config ML experiment tracker"
readme = "README.md"
authors = [
    { name = "Avik Arefin", email = "avik.me.arefin@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []
license = {text = "Apache-2.0"}
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: System :: Logging",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
Repository = "https://github.com/AvikArefin/mtrick"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"
