import socket
import http.server
import socketserver
import json
import os
import urllib.parse
import argparse
from typing import Any


def local_network_ip() -> None:
    # Create a dummy socket to find the interface used for external routing
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # We use a public IP address (Google's DNS) and port.
        # No actual connection or packet is sent over the network.
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
    except Exception:
        # Fallback to loopback if no active network connection exists
        local_ip = "127.0.0.1"
    finally:
        s.close()
        print(f"Local Network IP Address: {local_ip}")

        
class DashboardServer(socketserver.TCPServer):
    allow_reuse_address = True

    def __init__(
        self, server_address, handler_class, tracker_dir="metrics", verbose=False
    ):
        self.tracker_dir = tracker_dir
        self.verbose = verbose

        super().__init__(server_address, handler_class)


class DashboardHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        parsed_path = urllib.parse.urlparse(self.path)
        assert isinstance(self.server, DashboardServer)
        tracker_dir: str = self.server.tracker_dir

        # API Endpoint to get all runs
        if parsed_path.path == "/api/runs":
            self.send_response(200)
            self.send_header("Content-type", "application/json; charset=utf-8")
            # Add CORS headers just in case
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()

            runs: list[dict[str, str | int | list[str]]] = []
            if os.path.exists(tracker_dir):
                for dir_name in sorted(os.listdir(tracker_dir)):
                    dir_path: str = os.path.join(tracker_dir, dir_name)
                    if os.path.isdir(dir_path):
                        meta_path: str = os.path.join(dir_path, "meta.json")
                        meta: dict[str, str | int | float] = {}
                        
                        # Autogenerated Metadata loading 
                        if os.path.exists(meta_path):
                            with open(meta_path, "r") as f:
                                meta = json.load(f)
                        else:
                            meta = {"experiment_name": dir_name, "timestamp": "Unknown"}

                        # Folder name metadata
                        meta["folder"] = dir_name

                        # Files included metadata
                        try:
                            meta["files"] = os.listdir(dir_path)
                        except Exception:
                            meta["files"] = []

                        runs.append(meta)

            if self.server.verbose:
                print(json.dumps(runs, indent=4))
            self.wfile.write(json.dumps(runs).encode("utf-8"))
            return


        # Serve the dashboard index for root path
        elif parsed_path.path == "/":
            self.send_response(200)
            self.send_header("Content-type", "text/html; charset=utf-8")
            self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
            self.end_headers()

            static_dir: str = os.path.join(os.path.dirname(__file__), "static")
            index_path: str = os.path.join(static_dir, "index.html")

            with open(index_path, "rb") as f:
                self.wfile.write(f.read())
            return

        # Serve run data files from tracker directory
        else:
            # only serve files that resolve inside TRACKER_DIR
            requested: str = urllib.parse.unquote(parsed_path.path).lstrip("/")
            tracker_root: str = os.path.realpath(tracker_dir)
            local_path: str = os.path.realpath(os.path.join(tracker_dir, requested))
            if not local_path.startswith(tracker_root + os.sep) or not os.path.isfile(
                local_path
            ):
                self.send_error(404, "Not Found")
                return
            self.send_response(200)
            if local_path.endswith(".json") or local_path.endswith(".jsonl"):
                content_type = "application/json; charset=utf-8"
            else:
                content_type = "text/plain; charset=utf-8"
            self.send_header("Content-type", content_type)
            self.end_headers()
            with open(local_path, "rb") as f:
                self.wfile.write(f.read())

    def do_POST(self):
        parsed_path = urllib.parse.urlparse(self.path)
        assert isinstance(self.server, DashboardServer)
        tracker_dir: str = self.server.tracker_dir

        if parsed_path.path.startswith("/api/runs/") and parsed_path.path.endswith("/note"):
            parts = parsed_path.path.split("/")
            if len(parts) == 5:
                folder_name = urllib.parse.unquote(parts[3])
                
                content_length = int(self.headers.get("Content-Length", 0))
                body = self.rfile.read(content_length).decode("utf-8")
                
                try:
                    data = json.loads(body)
                    note = data.get("note", "")
                    
                    meta_path = os.path.join(tracker_dir, folder_name, "meta.json")
                    if os.path.exists(meta_path):
                        with open(meta_path, "r") as f:
                            meta = json.load(f)
                        meta["note"] = note
                        with open(meta_path, "w") as f:
                            json.dump(meta, f, indent=4)
                            
                        self.send_response(200)
                        self.send_header("Content-type", "application/json")
                        self.end_headers()
                        self.wfile.write(json.dumps({"status": "ok"}).encode("utf-8"))
                        return
                except Exception as e:
                    self.send_error(400, f"Bad Request: {e}")
                    return
        
        self.send_error(404, "Not Found")



def main():
    local_network_ip()

    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000, help="Port to run on")
    parser.add_argument(
        "--tracker-dir",
        type=str,
        default="metrics",
        help="Local directory to scan for experiment logs",
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose debug output (e.g. formatted runs JSON)",
    )
    args = parser.parse_args()

    with DashboardServer(
        ("", args.port), DashboardHandler, tracker_dir=args.tracker_dir, verbose=args.verbose
    ) as httpd:
        print(f"Dashboard is live! Ctrl / Cmd Click >>> http://localhost:{args.port} <<<")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down dashboard...")


if __name__ == "__main__":
    main()
