import os
import re
import json
import subprocess
from datetime import datetime

class MTracker:
    def __init__(
        self,
        experiment_name: str,
        save_path: str = "metrics",
    ):
        self.experiment_name = experiment_name
        self.save_path = save_path

        # Autogenerated metadata
        self.timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.git_commit: str = self.get_git_commit()

        # Determine experiment number from the highest existing exp* directory
        os.makedirs(self.save_path, exist_ok=True)
        self.experiment_number = self.get_experiment_number()

        dir_name = f"exp{self.experiment_number:03d}_{self.experiment_name}_{self.timestamp}"
        self.experiment_dir = os.path.join(self.save_path, dir_name)
        try:
            os.mkdir(self.experiment_dir)
        except FileExistsError:
            raise RuntimeError(
                f"Failed to create a unique run directory {self.save_path}"
            )

        # Metadata dump
        self.meta = {
            "experiment_name": self.experiment_name,
            "experiment_number": self.experiment_number,
            "timestamp": self.timestamp,
            "git_commit": self.git_commit,
        }
        with open(os.path.join(self.experiment_dir, "meta.json"), "w") as f:
            json.dump(self.meta, f, indent=4)

        print(f"Tracking experiment at: {self.experiment_dir}")

    def get_git_commit(self) -> str:
        """Returns the current short git commit hash, appending '-dirty' if uncommitted changes exist."""
        try:
            commit_hash = (
                subprocess.check_output(["git", "rev-parse", "--short", "HEAD"])
                .decode("ascii")
                .strip()
            )
            status = (
                subprocess.check_output(["git", "status", "--porcelain"])
                .decode("ascii")
                .strip()
            )
            if status:
                return f"{commit_hash}-dirty"
            return commit_hash
        except Exception:
            return "unknown"

    def get_experiment_number(self) -> int:
        max_exp_num = 0
        for path in os.listdir(self.save_path):
            match = re.match(r"^exp(\d+)_", path)
            if match:
                max_exp_num = max(max_exp_num, int(match.group(1)))

        return max_exp_num + 1


    def log(
        self,
        metrics: dict[str, float],
        epoch: int,
    ):
        """
        Simplified logging API.
        """
        formatted_metrics = ", ".join(f"{k}: {v:.4f}" for k, v in metrics.items())
        print(f"{epoch:4d}| {formatted_metrics}")

        log_entry: dict[str, float] = {"epoch": epoch, **metrics}
        metrics_path = os.path.join(self.experiment_dir, "metrics.jsonl")
        with open(metrics_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")

        

    def log_trajectory(
        self,
        true_data: list[list[float]],
        pred_data: list[list[float]],
    ):
        """
        Saves a 2D trajectory of ground truth vs predicted data to a JSON file.
        true_data: numpy array of shape (seq_len, 2+)
        pred_data: numpy array of shape (seq_len, 2+)
        """
        data: dict[str, list[list[float]]] = {
            "true": [[float(p[0]), float(p[1])] for p in true_data],
            "pred": [[float(p[0]), float(p[1])] for p in pred_data]
        }

        filename = "trajectory.json"
        json_path = os.path.join(self.experiment_dir, filename)

        with open(json_path, "w") as f:
            json.dump(data, f)


    def log_confusion_matrix(
        self,
        matrix_data,
        classes=None,
        title="Confusion Matrix",
        filename="confusion.jsonl",
    ):
        """
        Saves a confusion matrix to JSONL.
        matrix_data: 2D numpy array or nested list [true_class][pred_class]
        classes: List of string labels for the classes.
        """
        jsonl_path = os.path.join(self.experiment_dir, filename)
        num_classes = len(matrix_data)
        if classes is None:
            classes = [f"Class {i}" for i in range(num_classes)]

        with open(jsonl_path, "w") as f:
            for i in range(num_classes):
                for j in range(num_classes):
                    row = {
                        "true_class": i,
                        "pred_class": j,
                        "count": int(matrix_data[i][j]),
                        "true_label": str(classes[i]),
                        "pred_label": str(classes[j])
                    }
                    f.write(json.dumps(row) + "\n")

        print(f"Saved confusion matrix: {jsonl_path}")
